[package]
name = "jobs_journal"
version = "0.1.4-alpha"
description = "A simple open-source job tracking application"
authors = ["Rossano Guenci"]
edition = "2024"
rust-version = "1.87.0"

# Set the default binary to run
default-run = "jobs_journal"

[[bin]]
name = "jobs_journal"
path = "src/main.rs"

[features]
dev = []
cli = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "jobs_journal"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.4.1", features = [] }

[dependencies]
ts-rs = "11.0.1"
serde = { version = "1.0.225", features = ["derive"] }
log = "0.4.28"
tauri = { version = "2.8.5", features = [] }
tauri-plugin-log = "2.7.0"
tokio = { version = "1.47.1", features = ["full"] }
sqlx = { version = "0.8.6", features = ["sqlite", "chrono", "runtime-tokio"] }
serde_json = "1.0.145"
tauri-plugin-opener = "2.5.0"
uuid = { version = "1.18.1", features = ["v4"] }
tauri-plugin-dialog = "2.4.0"
csv = "1.3.1"
chrono = "0.4.42"
env_logger = "0.11.8"
base64 = "0.22.1"
once_cell = "1.21.3"
tauri-plugin-fs = "2.4.2"
image = "0.25.8"
