[package]
name = "jobs_journal_dev_tools"
version = "0.1.1-alpha"
edition = "2024"

[[bin]]
name = "seed_db"
path = "src/seed_db.rs"
required-features = ["cli"]

[features]
cli = []
dev = []

[dependencies]
tokio = { version = "1.45.0", features = ["full"] }
sqlx = { version = "0.8.6", features = ["sqlite", "chrono", "runtime-tokio"] }
rand = "0.9.1"
chrono = "0.4.41"
serde_json = "1.0.140"
uuid = { version = "1.17.0", features = ["v4"] }
