// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobEvent = { id?: string, job_id: string, date_of_event: string, description: string, insert_type?: string, insert_date?: string, };
