// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobEntryMeta = { period_id?: string, note?: string, location?: string, link_to_job_posting?: string, };
