// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobEntryMeta } from "./JobEntryMeta";

export type JobInsert = { id?: string, insert_date?: string, company: string, title: string, application_date?: string, status?: string, insert_status?: string, meta?: JobEntryMeta, };
