// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobUpdate = { id: bigint, company: string | null, title: string | null, link: string | null, application_date: string | null, status: string | null, };
