// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobPeriod } from "./JobPeriod";

/**
 * Response payload for [`get_periods`].
 *
 * - `periods` contains all stored periods.
 * - `selected` is the currently selected period id (empty string if none).
 */
export type PeriodsResponse = { 
/**
 * All stored job periods.
 */
periods: Array<JobPeriod>, 
/**
 * The currently selected period id (maybe empty if none selected).
 */
selected: string, };
