// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StepResult } from "./StepResult";

/**
 * Aggregated results of running all startup steps.
 */
export type RunResult = { 
/**
 * The ordered list of step outcomes.
 */
steps: Array<StepResult>, };
