// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The outcome of a single startup step.
 */
export type StepResult = { 
/**
 * A unique key identifying the step (e.g., "ensure_periods").
 */
key: string, 
/**
 * Whether the step resulted in a change to state or data.
 */
changed: boolean, 
/**
 * A human-readable message describing what the step did.
 */
message: string, };
